apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: entertainment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.11.6
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /config
        - name: videos
          mountPath: /data/videos
        - name: tv
          mountPath: /data/tv
        ports:
        - containerPort: 8096
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: videos
        persistentVolumeClaim:
          claimName: jellyfin-videos
      - name: tv
        persistentVolumeClaim:
          claimName: sonarr-tv
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: entertainment
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096