apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-download
  namespace: entertainment
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 40Gi