apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: entertainment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
            - name: TZ
              value: Europe/Dublin
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: tv
          persistentVolumeClaim:
            claimName: sonarr-tv
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-download
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: entertainment
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      targetPort: 8989