apiVersion: v1
kind: Service
metadata:
  name: jellyfin-nodeport
  namespace: entertainment
spec:
  type: NodePort
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      nodePort: 30096
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-nodeport
  namespace: entertainment
spec:
  type: NodePort
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      targetPort: 7878
      nodePort: 30788
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-nodeport
  namespace: entertainment
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-nodeport
  namespace: entertainment
spec:
  type: NodePort
  selector:
    app: jackett
  ports:
    - name: http
      port: 9117
      targetPort: 9117
      nodePort: 30117