apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project (root / bootstrap)

  sourceRepos:
    - '*'

  destinations:
    - server: '*'
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'