apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/pkeshi-s-castle/argo-cd.git
    targetRevision: main
    path: apps/workloads/arr-stack/
  destination:
    server: https://192.168.86.32:6443
    namespace: entertainment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
