apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lazylibrarian
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pkeshi-s-castle/argo-cd.git
    targetRevision: main
    path: apps/workloads/lazylibrarian
  destination:
    server: https://kubernetes.default.svc
    namespace: lazylibrarian
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
